# Generated by Django 4.1.7 on 2023-03-26 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0002_timeofshift_remove_shift_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeofshift',
            name='afternoon',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='timeofshift',
            name='morning',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='timeofshift',
            name='night',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
