# Generated by Django 2.1.7 on 2023-03-30 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0006_auto_20230329_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Employee'),
        ),
    ]
