# Generated by Django 2.1.7 on 2023-03-30 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_permissions',
        ),
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=models.ImageField(default=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
